### ISSUE TITLE
doubts

### ISSUE THREAD

**Issue by Melvinbaby** [lucky-wfw/ARM_AMBA_Design#1]
Hello, I am melvin. I have certain doubts in apb protocol. Could you mention what does the following variables mean in_valid, d_out. Are read and write functions inbuild but i am not able to see their outputs. Can you give a small breif on the idea u designed apb protocol. 
Is it like the master add the two numbers and transmit it to the slaves

**Comment by lucky-wfw** [comment]
Thank you for your question.
First, the apb_master reads two pieces of data, din_a and din_b, from the previous module, performs the addition operation, and then writes the result to the subsequent apb_slave for storage. Therefore, a valid signal is needed to indicate when din_a and din_b can be read.The valid signal is in_valid, look at line 69.
Secondly, APB protocol has two types of read and write operations. Correspondently, APB_master can write data to APB_SLAVE or read data from the slave. Which operation to perform is determined according to the high and low level of PWRITE signal.When performing a read operation, the master reads data from the slave at the corresponding address and outputs it from the dout port. See lines 161, 191, 198, 205, etc.
In addition, it is important to note that the APB_MASTER module contains the instantiation of APB_SLAVE. When the IN_VALID signal is valid, after the addition operation, the flag of the signal changes to a high level, and then the state of the state machine switches. See line 97.
The above is the answer to your question.
Feel free to share your ideas.

**Comment by Nanda200** [comment]
> Thank you for your question. First, the apb_master reads two pieces of data, din_a and din_b, from the previous module, performs the addition operation, and then writes the result to the subsequent apb_slave for storage. Therefore, a valid signal is needed to indicate when din_a and din_b can be read.The valid signal is in_valid, look at line 69. Secondly, APB protocol has two types of read and write operations. Correspondently, APB_master can write data to APB_SLAVE or read data from the slave. Which operation to perform is determined according to the high and low level of PWRITE signal.When performing a read operation, the master reads data from the slave at the corresponding address and outputs it from the dout port. See lines 161, 191, 198, 205, etc. In addition, it is important to note that the APB_MASTER module contains the instantiation of APB_SLAVE. When the IN_VALID signal is valid, after the addition operation, the flag of the signal changes to a high level, and then the state of the state machine switches. See line 97. The above is the answer to your question. Feel free to share your ideas.

The instatntiated APB_slave1 code is not provide. Where can we find that code.
